app:
  token:
    secret: mdajLhQvlMXigj2NvzypqRA/uS5FUD7WsiaQiRW4kvf5EYhwDCsNqONGfvl//FX81LNfObsJ32YXwmpCY9KrND8cuWoCH8bngvy71lm3nL0lcvSNZrNPUZOAHNae8FEdn92IIeZxq9NtXP/sXNiRHOgSsK0rYbcX1ozU0uwIh5XgPSgeWOPzck9K+tp9QdalGVzxbv/E97GN7ToEWgI82B6J+1s12ojmojfN1Bh1mt6yD/iZv+YCbMWy4OoW9GvpR8HZ9A7mOpV/7FN4Ffq42EE0FYgXkj4yMakeLqpNh6faPMeqaZhiPfvNR5kDN96WmoijNSViOk9IdWkeYb/1
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: **email**
    password: **your password**
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_template
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
flyway:
  url: jdbc:postgresql://localhost:5432/auth_service_template
  schemas: auth_service_template
  user: postgres
  password: postgres